name: Building Secrets

on: [push,pull_request]

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
    - name: Api key security
      run: echo "Secret is ${{ secrets.API_KEY }}"
    - name: database password
      run: echo "Secret is ${{ secrets.DB_PASS }}"
    - name: environmental variable
      run: echo "Secret is ${{ secrets.ENV_VAR }}"
